package config

type NetworkInfo struct {
	BuildDatetime                       string  `yaml:"build_datetime"`
	KpClientDebugDisableDecoyTraffic    bool    `yaml:"kp_client_debug_DisableDecoyTraffic"`
	KpClientDebugEnableTimeSync         bool    `yaml:"kp_client_debug_EnableTimeSync"`
	KpClientDebugInitialMaxPKIDelay     int     `yaml:"kp_client_debug_InitialMaxPKIRetrievalDelay"`
	KpClientDebugPollingInterval        int     `yaml:"kp_client_debug_PollingInterval"`
	KpClientDebugSessionDialTimeout     int     `yaml:"kp_client_debug_SessionDialTimeout"`
	KpConfigKem                         string  `yaml:"kp_config_kem"`
	KpConfigLambdaD                     float64 `yaml:"kp_config_LambdaD"`
	KpConfigLambdaDMaxDelay             uint64  `yaml:"kp_config_LambdaDMaxDelay"`
	KpConfigLambdaGMaxDelay             uint64  `yaml:"kp_config_LambdaGMaxDelay"`
	KpConfigLambdaL                     float64 `yaml:"kp_config_LambdaL"`
	KpConfigLambdaLMaxDelay             uint64  `yaml:"kp_config_LambdaLMaxDelay"`
	KpConfigLambdaM                     float64 `yaml:"kp_config_LambdaM"`
	KpConfigLambdaMMaxDelay             uint64  `yaml:"kp_config_LambdaMMaxDelay"`
	KpConfigLambdaP                     float64 `yaml:"kp_config_LambdaP"`
	KpConfigLambdaPMaxDelay             uint64  `yaml:"kp_config_LambdaPMaxDelay"`
	KpConfigLogLevel                    string  `yaml:"kp_config_log_level"`
	KpConfigMu                          float64 `yaml:"kp_config_Mu"`
	KpConfigMuMaxDelay                  uint64  `yaml:"kp_config_MuMaxDelay"`
	KpConfigNike                        string  `yaml:"kp_config_nike"`
	KpConfigRatchetNike                 string  `yaml:"kp_config_ratchetNike"`
	KpConfigPkiSignatureScheme          string  `yaml:"kp_config_pkiSignatureScheme"`
	KpConfigSendRatePerMinute           uint64  `yaml:"kp_config_SendRatePerMinute"`
	KpConfigUserForwardPayloadLength    int     `yaml:"kp_config_UserForwardPayloadLength"`
	KpConfigWirekem                     string  `yaml:"kp_config_wirekem"`
	KpDebugConnectTimeout               int     `yaml:"kp_debug_ConnectTimeout"`
	KpDebugDecoySlack                   int     `yaml:"kp_debug_DecoySlack"`
	KpDebugDisableRateLimit             bool    `yaml:"kp_debug_DisableRateLimit"`
	KpDebugGatewayDelay                 int     `yaml:"kp_debug_GatewayDelay"`
	KpDebugGenerateOnly                 bool    `yaml:"kp_debug_GenerateOnly"`
	KpDebugHandshakeTimeout             int     `yaml:"kp_debug_HandshakeTimeout"`
	KpDebugKaetzchenDelay               int     `yaml:"kp_debug_KaetzchenDelay"`
	KpDebugNumGatewayWorkers            int     `yaml:"kp_debug_NumGatewayWorkers"`
	KpDebugNumKaetzchenWorkers          int     `yaml:"kp_debug_NumKaetzchenWorkers"`
	KpDebugNumServiceWorkers            int     `yaml:"kp_debug_NumServiceWorkers"`
	KpDebugNumSphinxWorkers             int     `yaml:"kp_debug_NumSphinxWorkers"`
	KpDebugReauthInterval               int     `yaml:"kp_debug_ReauthInterval"`
	KpDebugSchedulerExternalMemoryQueue bool    `yaml:"kp_debug_SchedulerExternalMemoryQueue"`
	KpDebugSchedulerMaxBurst            int     `yaml:"kp_debug_SchedulerMaxBurst"`
	KpDebugSchedulerQueueSize           int     `yaml:"kp_debug_SchedulerQueueSize"`
	KpDebugSchedulerSlack               int     `yaml:"kp_debug_SchedulerSlack"`
	KpDebugSendDecoyTraffic             bool    `yaml:"kp_debug_SendDecoyTraffic"`
	KpDebugSendSlack                    int     `yaml:"kp_debug_SendSlack"`
	KpDebugServiceDelay                 int     `yaml:"kp_debug_ServiceDelay"`
	KpDebugUnwrapDelay                  int     `yaml:"kp_debug_UnwrapDelay"`
	KpMiscTopologyLayers                int     `yaml:"kp_misc_topology_layers"`
	KpMiscTransport                     string  `yaml:"kp_misc_transport"`
	KpPluginMaxConcurrency              int     `yaml:"kp_plugin_MaxConcurrency"`
	NetworkID                           string  `yaml:"network_id"`
	VersionDeployer                     string  `yaml:"version_deployer"`
	VersionKatzenpost                   string  `yaml:"version_katzenpost"`
	VersionZknOpt                       string  `yaml:"version_zkn_opt"`
}
