[Networks]
  "base" = "https://base-rpc.publicnode.com"
  "base/sepolia" = "https://base-sepolia-rpc.publicnode.com"
  "bitcoin" = "https://bitcoin-rpc.publicnode.com"
  "bitcoin/testnet" = "https://rpc.ankr.com/btc_signet"
  "bsc" = "https://bsc-rpc.publicnode.com"
  "bsc/testnet" = "https://bsc-testnet-rpc.publicnode.com"
  "ethereum" = "https://ethereum-rpc.publicnode.com"
  "ethereum/sepolia" = "https://ethereum-sepolia-rpc.publicnode.com"
  "mina" = "https://proxy.minaexplorer.com/graphql"
  "mina/devnet" = "https://proxy.devnet.minaexplorer.com/graphql"
  "polygon" = "https://polygon-bor-rpc.publicnode.com"
  "polygon/amoy" = "https://polygon-amoy-bor-rpc.publicnode.com"
  "secret" = "https://rpc.ankr.com/scrt"
  "secret/testnet" = "https://rpc.pulsar.scrttestnet.com"
  "solana" = "https://solana-rpc.publicnode.com"
  "solana/devnet" = "https://rpc.ankr.com/solana_devnet"
  "xdc" = "https://erpc.xinfin.network"
  "xdc/apothem" = "https://earpc.apothem.network"
