[Networks]
  "bitcoin" = "https://bitcoin-rpc.publicnode.com"
  "bitcoin/testnet" = "https://rpc.ankr.com/btc_signet"
  "ethereum" = "https://ethereum-rpc.publicnode.com"
  "ethereum/sepolia" = "https://ethereum-sepolia-rpc.publicnode.com"
  "mina" = "https://proxy.minaexplorer.com/graphql"
  "mina/devnet" = "https://proxy.devnet.minaexplorer.com/graphql"
  "secret" = "https://rpc.ankr.com/scrt"
  "secret/testnet" = "https://rpc.pulsar.scrttestnet.com"
  "solana" = "https://solana-rpc.publicnode.com"
  "solana/devnet" = "https://rpc.ankr.com/solana_devnet"
