[Server]
  Identifier = "servicenode1"
  WireKEM = "xwing"
  PKISignatureScheme = "Ed25519"
  Addresses = ["tcp://127.0.0.1:30009"]
  MetricsAddress = "127.0.0.1:30010"
  DataDir = "/appchain_mixnet/servicenode1"
  IsGatewayNode = false
  IsServiceNode = true

[Logging]
  Disable = false
  File = "katzenpost.log"
  Level = "DEBUG"

[ServiceNode]

  [[ServiceNode.Kaetzchen]]
    Capability = "echo"
    Endpoint = "+echo"
    Disable = false

  [[ServiceNode.Kaetzchen]]
    Capability = "testdest"
    Endpoint = "+testdest"
    Disable = false

  [[ServiceNode.CBORPluginKaetzchen]]
    Capability = "spool"
    Endpoint = "+spool"
    Command = "/appchain_mixnet/memspool.alpine"
    MaxConcurrency = 1
    Disable = false
    [ServiceNode.CBORPluginKaetzchen.Config]
      data_store = "/appchain_mixnet/servicenode1/memspool.storage"
      log_dir = "/appchain_mixnet/servicenode1"

  [[ServiceNode.CBORPluginKaetzchen]]
    Capability = "pigeonhole"
    Endpoint = "+pigeonhole"
    Command = "/appchain_mixnet/pigeonhole.alpine"
    MaxConcurrency = 1
    Disable = false
    [ServiceNode.CBORPluginKaetzchen.Config]
      db = "/appchain_mixnet/servicenode1/map.storage"
      log_dir = "/appchain_mixnet/servicenode1"

  [[ServiceNode.CBORPluginKaetzchen]]
    Capability = "panda"
    Endpoint = "+panda"
    Command = "/appchain_mixnet/panda_server.alpine"
    MaxConcurrency = 1
    Disable = false
    [ServiceNode.CBORPluginKaetzchen.Config]
      fileStore = "/appchain_mixnet/servicenode1/panda.storage"
      log_dir = "/appchain_mixnet/servicenode1"
      log_level = "DEBUG"

  [[ServiceNode.CBORPluginKaetzchen]]
    Capability = "http"
    Endpoint = "+http"
    Command = "/appchain_mixnet/proxy_server.alpine"
    MaxConcurrency = 1
    Disable = false
    [ServiceNode.CBORPluginKaetzchen.Config]
      host = "localhost:4242"
      log_dir = "/appchain_mixnet/servicenode1"
      log_level = "DEBUG"

[PKI]
  [PKI.Voting]

    [[PKI.Voting.Authorities]]
      Identifier = "auth2"
      IdentityPublicKey = "-----BEGIN ED25519 PUBLIC KEY-----\nP+IEU34Od+kIaPQrxPNk1CrA0o2t0whHDBj8CEzbIVY=\n-----END ED25519 PUBLIC KEY-----\n"
      PKISignatureScheme = "Ed25519"
      LinkPublicKey = "-----BEGIN XWING PUBLIC KEY-----\nMFVYEVG2SuWLrUlI+li4cgt0CoprqGQtYehOIABVjyAdKSVxB8CVSdgfmuqMikk3\nQYNJ91Ut12nCsPi4qqNXPuJqPda4Byg4zlE25PdtxbI71yIIj6C8SKZ6jtlNRnW9\nuGMfbuKFbUZRlmGrF/dybnnLmWvGsAZ3E5BQCADClVQHRmg5uLjLGdtzDHkcoOJ3\niKZA5OIjMTFUeQM13GCNeJJmuAVXUZIQF3wi4vOVXwcxszpDtQq+o/JQ31DJYUtb\nu8izLuyarVOolTuQKqDOJBi5NxllvpGbQsEokrSWPXpa3uMFrzqPO0aWMAwJs5CQ\n3sOXuukKp8tYuxlLHyE0hosNrPZxrShK0AtTH8CwrAE+mdiLKZSsybFyUFbPAKfA\nONwp6xYxlmdPJmMJQjvGWEkoeRglWiYhOOhaVXeYq+es7GIIbbsGCtiHPLkj9JhI\ncoBkfZZxHpFtkOMR8MfAhqy3Qzy49BS1EngmobTIrKFVctersgcD4wBnh7dpfsQi\nN0qfNbKKbQgjUqK+qnrKLuaX4gXEOUY1PMdRCEyhT4p0FJBY9yl6tqWmilVjSIrL\nFEoRQWybPII2+wVoH4tZEQyRLViIoFnFOcBZYVSu4IO71nw+DWWZH1TF5+I+XsS7\n8EiWtDQpI/nFoIQWMkYocXa6YvFO6xqGGFNTqQEWzHqDnIIMN3rMdSgmxicIM/G0\nUOp2JFJRMdlkrLg8yuaL0doJn9Yiddl3nYGlKnfKULJwhOEP+MtKQgdW1qSDmEEn\nYTEHoVKKQZGkhgZs4YJH6MVMJuhNPmF76OywHOhWDKlhf2MuiMhYQnosKWwfOowB\nQ5u7XjOotekZkEE4ZYBlkHJikXJfHhq6WBdGwzYtAit14JyGqHC0NYp/nKWE+0E1\n5GjFlch0UkFoWuwDYWVEDbjLgLawkhbK09gIzkJd98iIMpldU0gv3nGz0WloT8W0\nVPIbGniXnLVQ/BmcQwMuyPJfCDmc+aqDjZbJMyt7PbqmLke4+be77GwPZfio3lJU\nvHtwh5ifTrZzkVAFbOzKLlREOpGwcnkg7lGkdGB27fvOfUNumqh7MJSbiduiuFAs\nxzxzesOhRkCgYHyxgwEfhNQRBLAvJwVYeRwHHpwlvOFSL/Vscoe4iCS9GoXKOrVp\n49XGgfyCATQOo6Up3UsCGEtgavaJ3sY0MjCAR+yi0Hsitna+aZYs+qIuLqZxC+e/\ncPqBPEwBQtwnOseTW9aIxeOe8zHAzKvKvCnNVykJbmhRLzpO+COuukslXdptK2e/\nPHhjyXEiXJMieHeG+Uldk+jBwyeb86ZHTpS2zPyLsDR+VCVIu1Z/STDAFduJfrOx\n90OTRZW43MwQ27xU/DySztWECAdXGQhzXNNa3jiAW1rNXTojh1GowiU/UPhOOxtf\nBwuCMtrKRDwmbVG5/gM3SaMjyENUtmSXx9E1d2a7NHu6rdQ91qKtvBzDFeYKDueu\nD5UekwWCATN5BmoSH3aeCtl1aDIy+ui6dQyG3QlszaYXE8lgMQNLppawCPyXEYue\nITFBbiDZKgGEMWMMsiwHVluu00Pf7bPbVOngbgBggGrN6IwOhwz4UnOQX6FzafKZ\nChFrGaeIYr+TlVwNFSuFKg==\n-----END XWING PUBLIC KEY-----\n"
      WireKEMScheme = "xwing"
      Addresses = ["tcp://127.0.0.1:30002"]

[Management]
  Enable = true
  Path = "/appchain_mixnet/servicenode1/management_sock"

[SphinxGeometry]
  PacketLength = 31082
  NrHops = 5
  HeaderLength = 476
  RoutingInfoLength = 410
  PerHopRoutingInfoLength = 82
  SURBLength = 572
  SphinxPlaintextHeaderLength = 2
  PayloadTagLength = 32
  ForwardPayloadLength = 30574
  UserForwardPayloadLength = 30000
  NextNodeHopLength = 65
  SPRPKeyMaterialLength = 64
  NIKEName = "x25519"
  KEMName = ""

[Debug]
  NumSphinxWorkers = 20
  NumServiceWorkers = 3
  NumGatewayWorkers = 3
  NumKaetzchenWorkers = 4
  SchedulerExternalMemoryQueue = false
  SchedulerQueueSize = 0
  SchedulerMaxBurst = 16
  UnwrapDelay = 250
  GatewayDelay = 500
  ServiceDelay = 500
  KaetzchenDelay = 750
  SchedulerSlack = 150
  SendSlack = 50
  DecoySlack = 15000
  ConnectTimeout = 60000
  HandshakeTimeout = 30000
  ReauthInterval = 30000
  SendDecoyTraffic = false
  DisableRateLimit = false
  GenerateOnly = false
