[Server]
  Identifier = "mix2"
  WireKEM = "xwing"
  PKISignatureScheme = "Ed25519"
  Addresses = ["tcp://127.0.0.1:30013"]
  MetricsAddress = "127.0.0.1:30014"
  DataDir = "/appchain_mixnet/mix2"
  IsGatewayNode = false
  IsServiceNode = false

[Logging]
  Disable = false
  File = "katzenpost.log"
  Level = "DEBUG"

[PKI]
  [PKI.Voting]

    [[PKI.Voting.Authorities]]
      Identifier = "auth4"
      IdentityPublicKey = "-----BEGIN ED25519 PUBLIC KEY-----\nqo4p8HugC6NvKfMMmdMkxZcYxZw6BEJtAlgHVyinhyI=\n-----END ED25519 PUBLIC KEY-----\n"
      PKISignatureScheme = "Ed25519"
      LinkPublicKey = "-----BEGIN XWING PUBLIC KEY-----\nUnUOftB1/yCYJiUCO1E92bpcgWuAv+Z4TqvF9nS4RPm8sRmZTHPCzlwg1oV3/tWk\nhxUGZ/Ia03cQx4swUsl5n+anOChbfokgafpcrQhI/6lHj6ZcrpvKq2Ok9BLK0bRK\nYJAhcYp517ct+ZgJZnoua2Gjnacl8mRyEFXG+xNtUhgzuFIAYBuyPUpZEzS0aWq7\nhUQfxxh9TVudxYQhuqUbyJXCAuxuaDqyywW8bSqJ/vA509RdFag2bNuXhmfM8SnC\nvyZP8NVavJGv1AVq8RMkOlebOmV8kVJUGWVZBSsScJQXA2dI8IQ594Kzp4jOHuMq\nHAyyDWlwJYmVcfmoYIG8ySXP7blC9FYkExWY2sU87nxr0xBuyYOfx5kv+MRiucws\nREu257LNeKx4n+ymbzCXvkthaVdMO9uZYnsHA1RoPLBXEdXCKptv2wDIegyH9nPE\n5Jg2aCqgGrxakMcBLEuG0+YKORmAJFBv/1to1VW85/kvi2Nh9uMWDZFlwxVZWDeI\nB8B/sjueWCHOw1hDRTmlYNCcJQt/lniYzUdg+rnLOtvIT3ElylkIiLypmHlUJCGH\niqBIaBwisbYFbJOp9bRMK0A7gejJpMOLR3UlK6sD84hNepN7+1onsVqn4VGus9am\nX4SkWpFdJhgO1zGHHRCVc3nJXca7bEhHvohkoLtX7PFefGgtz/All1BciuWlEXV3\n0GB4j5obkDgw07wGp2mD5jiUpHELzyEOibQpy5S7Pik0/OFdz7OhueS2ALSjEdLB\nbMPAqyMlhNhLCbhpbTcKqJLFANmv0wkfKHTJ9xLLRKodnOFD+wwtYLuL5MNsQgsH\nY4FfWzbC0FSAIGG3HfUDqAlIZ1RkviI6w4GqU0Zt5Auqz9aPn0cLUAlbUVAjvCsb\npPWw6VGVktGhgBw7JLkCyAbI7ewSnfClbLRwyjJLJxCV0NCCUIx3BtZYRTiuuJEZ\ntHlmnDs2rnLC1byXgMVZ64Bpl0NeThxde2pnsZoUeMswrmtWgmxAdZQ4WxmpRqhr\nGTLOPgFzBlxMoPmWCSELTyWXPuZis8E++Zhlvyqt9wqhAmtJECxtePOPl6iXowKr\nmkBf17RRR7yCVRccXqnI2MxGVAg5KXg/+ZqsRIC2z5fBp8g/GOEYDhJDuKAtascu\nkvqxceFoACCmcmsZsoCCLNgf64p8Yxh3WEtDL2MwniFQQAEBfbYfE1qjoEHIWpY0\n9kzIxoxZ6XBinhcrE/BIMhJuCZa5RkoymSU+O3wdtkuMuOxgdTpacDsBbvIVwEST\nQcJ87KBCQkdyrttt4tzACqlugQgsn6Mh9uh2D8tZXrm0QUEhtTSaVtaNmMqnLul2\nLdKHSwytJCqHtvwPwUc48dKtxbFTYqAF2iirF5IQ2PJCBhqrgPYHFoYwyfA4YvF4\nJ0w0PcSty/EBIyyMlHxAzeZd3PXFI6cXIaAF1+K3krtEt2GktOR0xSFIn2heJTx0\nUgFU/0wmPUsEjqBDpoGusPnFkqWP5AK3NkuqnIsfvbzNiwNp2GiMDFVakVIYGBpC\njnXsn5gD2iDgcVTcP9uW9jdB7KWeN8+lmdc+08Lipf6OkjhR8Vqhf5+wdvokWSQG\nY5yxhPgik5wda7AiJ/hFCQ==\n-----END XWING PUBLIC KEY-----\n"
      WireKEMScheme = "xwing"
      Addresses = ["tcp://127.0.0.1:30004"]

[Management]
  Enable = false
  Path = "/appchain_mixnet/mix2/management_sock"

[SphinxGeometry]
  PacketLength = 31082
  NrHops = 5
  HeaderLength = 476
  RoutingInfoLength = 410
  PerHopRoutingInfoLength = 82
  SURBLength = 572
  SphinxPlaintextHeaderLength = 2
  PayloadTagLength = 32
  ForwardPayloadLength = 30574
  UserForwardPayloadLength = 30000
  NextNodeHopLength = 65
  SPRPKeyMaterialLength = 64
  NIKEName = "x25519"
  KEMName = ""

[Debug]
  NumSphinxWorkers = 20
  NumServiceWorkers = 3
  NumGatewayWorkers = 3
  NumKaetzchenWorkers = 3
  SchedulerExternalMemoryQueue = false
  SchedulerQueueSize = 0
  SchedulerMaxBurst = 16
  UnwrapDelay = 250
  GatewayDelay = 500
  ServiceDelay = 500
  KaetzchenDelay = 750
  SchedulerSlack = 150
  SendSlack = 50
  DecoySlack = 15000
  ConnectTimeout = 60000
  HandshakeTimeout = 30000
  ReauthInterval = 30000
  SendDecoyTraffic = false
  DisableRateLimit = false
  GenerateOnly = false
