version: "2"

services:

  gateway1:
    restart: "no"
    image: katzenpost-alpine_base
    volumes:
      - ./:/appchain_mixnet
    command: /appchain_mixnet/server.alpine -f /appchain_mixnet/gateway1/katzenpost.toml
    network_mode: host

    depends_on:
      - auth1
      - auth2
      - auth3
      - auth4
      - auth5
  servicenode1:
    restart: "no"
    image: katzenpost-alpine_base
    volumes:
      - ./:/appchain_mixnet
    command: /appchain_mixnet/server.alpine -f /appchain_mixnet/servicenode1/katzenpost.toml
    network_mode: host

    depends_on:
      - auth1
      - auth2
      - auth3
      - auth4
      - auth5
  mix1:
    restart: "no"
    image: katzenpost-alpine_base
    volumes:
      - ./:/appchain_mixnet
    command: /appchain_mixnet/server.alpine -f /appchain_mixnet/mix1/katzenpost.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
      - auth4
      - auth5
  mix2:
    restart: "no"
    image: katzenpost-alpine_base
    volumes:
      - ./:/appchain_mixnet
    command: /appchain_mixnet/server.alpine -f /appchain_mixnet/mix2/katzenpost.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
      - auth4
      - auth5
  mix3:
    restart: "no"
    image: katzenpost-alpine_base
    volumes:
      - ./:/appchain_mixnet
    command: /appchain_mixnet/server.alpine -f /appchain_mixnet/mix3/katzenpost.toml
    network_mode: host
    depends_on:
      - auth1
      - auth2
      - auth3
      - auth4
      - auth5
  auth1:
    restart: "no"
    image: katzenpost-alpine_base
    volumes:
      - ./:/appchain_mixnet
    command: /appchain_mixnet/voting.alpine -f /appchain_mixnet/auth1/authority.toml
    network_mode: host

  auth2:
    restart: "no"
    image: katzenpost-alpine_base
    volumes:
      - ./:/appchain_mixnet
    command: /appchain_mixnet/voting.alpine -f /appchain_mixnet/auth2/authority.toml
    network_mode: host

  auth3:
    restart: "no"
    image: katzenpost-alpine_base
    volumes:
      - ./:/appchain_mixnet
    command: /appchain_mixnet/voting.alpine -f /appchain_mixnet/auth3/authority.toml
    network_mode: host

  auth4:
    restart: "no"
    image: katzenpost-alpine_base
    volumes:
      - ./:/appchain_mixnet
    command: /appchain_mixnet/voting.alpine -f /appchain_mixnet/auth4/authority.toml
    network_mode: host

  auth5:
    restart: "no"
    image: katzenpost-alpine_base
    volumes:
      - ./:/appchain_mixnet
    command: /appchain_mixnet/voting.alpine -f /appchain_mixnet/auth5/authority.toml
    network_mode: host

  metrics:
    restart: "no"
    image: docker.io/prom/prometheus
    volumes:
      - ./:/appchain_mixnet
    command: --config.file="/appchain_mixnet/prometheus.yml"
    network_mode: host
