[Server]
  Identifier = "auth1"
  WireKEMScheme = "xwing"
  PKISignatureScheme = "Ed25519"
  Addresses = ["http://127.0.0.1:30001"]
  DataDir = "/appchain_mixnet/auth1"

[[Authorities]]
  Identifier = "auth1"
  IdentityPublicKey = "-----BEGIN ED25519 PUBLIC KEY-----\n+UxvgU96eikyTejEEx1jsddGTKWVxvHAdArs8xSX6+c=\n-----END ED25519 PUBLIC KEY-----\n"
  PKISignatureScheme = "Ed25519"
  LinkPublicKey = "-----BEGIN XWING PUBLIC KEY-----\ngmks0vyK5fUMY4jC0/AoSEBmBxJz5tIV2Cd2a5WtQPIl3VPLBPlRCBvIMvRvm2jN\n6CZE2gfB/RQA1alNeePBz5Ey7kpnWtE8iLuZ8iyAb2JjuogFCVoK4aEH4TKdOCV2\nDxocr+gHKZKFk8Bs/HhT4MpPjAxpiltaMyuqeFYfdESP6QM6cHbEo4gZSNnHmRa6\nDripCGdeTWc0vYeIQNlG9kdgJvE2+3Vwilq13tMdTAu5L9jAJWMdytiyqvOfqPc4\nstKlEkgcaIEjdeohRxBeG0fDl0UWboVqX0RXV5StDGtcLNXHi3ZnnPAPAbw7udyd\nFlmeTgalA8CUzEwH+bQLhuVk7cOHRsU1dzY76Ss7pekvOclKjHbKh0heJXnKI0iN\neFcrIRwlHIuju3m+QoNjsvZJc9egu6m7+bWW1WuQVITMTlhVxeEjY7jBx9N671x5\n1edIFQAMFDGzBsQLtTJpsZobBBXDNLMbv5BpecaGT1gpTPRM3kIFVueob1dvumLI\n1HwTITs69lyO3cSTz8UwV/A4FvEVP4I63DsncWUWDtsmG+M2AzPCketLptkUa2SN\nraRuPJFKzygQS2teNMOkWiS4d8SzVEAPxPRMfExuOilB9yGIaMcXr7i1tSvAy6JR\no6mBHhFCzwZ1+nGhEvSLCBaopKQD6jang2MlOGOwTkw1k0VIoOhyOacTUkWAohC8\n6iURe0vPvyyg1/SMJfiAd5WZzJQ0owCXcki+b2I77pIQ71Cq+9ctrCI4eVmISbWs\neKx9qvE5mjN/HTmpL8k9icq/wFlPbuy/eyOKM8GwZxxkGoZ/7NHEbgFPNKdvX0pb\n1PEA8ZCIYDc56TdWE8p/n/aUvCE8TrVan5oLjOMFy+tis/puWNK6hXJ+XwQ8v0ej\nDpoceMIvCmN4Tleb6HiX3yUDpyiXIemdP9FtckeGC0QTQJxaR3DIttx2ZeYIuYUn\ntIyftiee5MmWVgW4jZR1QCMhxRzEuHDIzlxDWSB9akZx5uNscwxdWrjIw5KMGQFd\nIyINqraRE6OPxMRrPkWPHmwtmKxeJVljVMaTIlpN7Ns45VQRXsOaHXBxkrpbmPgT\ng0HEloydDOZryQNzHxc0erBh1oAI3tZ/6YCUIDFVG7ytZcAx5TV+8YNVQ6pd0QCy\nNmN0VOgp5aRt66gd4/ECfKWh0CqP1cldO2iJdZxwfXXIXCJUpepww7J/09EdE6MW\nefZWhpa220AJvlydlqSJ//MFL1mGW6hld4srOkE6RUZoLSk2YLWyeFBbQ6BeL4mU\neFW/PGRPwhsNX7kH48EYXgKFEOecS5cDS5VbSKpn1jbEDBQS8XBz4mOTFWV0RwOu\n0HJD1/AOAJd3L1sI/eMjOlBqNuFlAjcI9EQLvoAn7/Wn3vo8V9pz2Lw1erh+kNYa\nWyZ1N4BJthQz3eqdTGTB+llc6bCFkkyBLHZWETxSQgINkuC9AwRkEWEp/cAF3OOJ\nM9ojIuXCxxGqxZRqGatZIEEJLpM+JwKVYaaR6fc6xbuQprdglYOaUZhYiwgZQPUR\nTSZy1kVtV7qVN7ZWmkAb/f5+B5WypR7fx7m2rb46Vk+C57TmcwkqvPD3EGN7nirn\ns1UiGj9vdCNcD2bbNlNgaQ==\n-----END XWING PUBLIC KEY-----\n"
  WireKEMScheme = "xwing"
  Addresses = ["http://127.0.0.1:30001"]

[Logging]
  Disable = false
  File = "katzenpost.log"
  Level = "DEBUG"

[Parameters]
  SendRatePerMinute = 0
  Mu = 0.005
  MuMaxDelay = 1000
  LambdaP = 0.001
  LambdaPMaxDelay = 1000
  LambdaL = 0.0005
  LambdaLMaxDelay = 1000
  LambdaD = 0.0005
  LambdaDMaxDelay = 3000
  LambdaM = 0.0005
  LambdaG = 0.0
  LambdaMMaxDelay = 100
  LambdaGMaxDelay = 100

[Debug]
  Layers = 3
  MinNodesPerLayer = 1
  GenerateOnly = false

[[GatewayNodes]]
  Identifier = "gateway1"
  IdentityPublicKeyPem = "../gateway1/identity.public.pem"

[Topology]

  [[Topology.Layers]]

    [[Topology.Layers.Nodes]]
      Identifier = "mix1"
      IdentityPublicKeyPem = "../mix1/identity.public.pem"

  [[Topology.Layers]]

    [[Topology.Layers.Nodes]]
      Identifier = "mix2"
      IdentityPublicKeyPem = "../mix2/identity.public.pem"

  [[Topology.Layers]]

    [[Topology.Layers.Nodes]]
      Identifier = "mix3"
      IdentityPublicKeyPem = "../mix3/identity.public.pem"

[SphinxGeometry]
  PacketLength = 31082
  NrHops = 5
  HeaderLength = 476
  RoutingInfoLength = 410
  PerHopRoutingInfoLength = 82
  SURBLength = 572
  SphinxPlaintextHeaderLength = 2
  PayloadTagLength = 32
  ForwardPayloadLength = 30574
  UserForwardPayloadLength = 30000
  NextNodeHopLength = 65
  SPRPKeyMaterialLength = 64
  NIKEName = "x25519"
  KEMName = ""
