name: build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  docker_mixnet_setup:
    runs-on: ubuntu-latest
    env:
      warped: true
      XDG_RUNTIME_DIR: /run
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure podman socket
        run: |
          sudo systemctl restart dbus && sudo systemctl enable --now podman.socket

      - name: Build and start the mixnet
        run: |
          cd docker && sudo -E make start

      - name: List All Containers
        run: |
          echo "Listing all Docker containers:"
          sleep 2
          sudo docker ps -a

      - name: Allow mixnet to settle
        run: |
          sleep 240

      - name: Verify Running Docker Containers
        run: |
          sleep 30  # Allow some time for all services to start up
          containers=$(sudo docker ps --format '{{.Names}}: {{.Status}}')
          echo "Running containers:"
          echo "$containers"
          if [[ $(echo "$containers" | wc -l) -lt 5 ]]; then  # Replace '5' with the expected number of running containers
            echo "Error: Not all Docker containers are running."
            exit 1
          else
            echo "All Docker containers are up and running."
