name: build
on:
  pull_request:
    branches:
      - '**'

jobs:
  docker_mixnet_setup:
    runs-on: ubuntu-latest
    env:
      warped: true
      XDG_RUNTIME_DIR: /run
    strategy:
      matrix:
        go-version: [1.22.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build everything to ensure it can be built
        run: |
          make all

      - name: Configure podman socket
        run: |
          sudo systemctl restart dbus && sudo systemctl enable --now podman.socket

      - name: Build and start the mixnet
        run: |
          cd docker && sudo -E make start wait

      - name: run ping
        run: cd docker && sudo -E make run-ping

      - name: run walletshield test probe
        run: cd docker && sudo -E make walletshield-probe

      - name: Start walletshield
        run: |
          cd docker
          sudo -E make walletshield-start
          sleep 10
          sudo -E make walletshield-logs
      
      - name: Test walletshield
        run: ./tests/e2e/walletshield/test.sh

      - name: Test walletshield request concurrency
        run: ./tests/e2e/walletshield/test-concurrent-requests.sh

      - name: Stop walletshield
        run: |
          cd docker
          sudo -E make walletshield-logs
          sudo -E make walletshield-stop

      - name: Stop the mixnet
        run: |
          cd docker && sudo -E make stop
